### ISSUE TITLE
VCPKG cmake toolchain file not added to cmake settings

### ISSUE THREAD

**Issue by kwsp** [JackBoosY/vcpkg-vscode-extension#2]
After I `enable manifest`, it seems the VCPKG toolchain file is not added to cmake config.

Could you please add more docs on how to use manifest mode? 
1. Do I need to manually create build directory first, run vcpkg install, before trying to build with cmake?
2. (I'm not very familiar with vscode-cmake-tools) It seems like [`vscode-cmake-tools` use `kits` to include toolchain files](https://github.com/microsoft/vscode-cmake-tools/blob/main/docs/kits.md). Would this package add a new `kit`? 

I know you're a maintainer of `vcpkg` and I thank you for all your work on vcpkg and related projects! I've been migrating all my projects over to `vcpkg` from `conan` (after they fumbled 2.0). I'd love to contribute to make the ecosystem better!

**Comment by kwsp** [comment]
Right now the easiest way to get vcpkg to work with cmake in VS Code is to add this to `.vscode/settings.json`

```json
{
    "cmake.configureArgs": [
        "-DVCPKG_MANIFEST_MODE=ON",
        "-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake",
    ],
    "cmake.generator": "Ninja",
}
```

**Comment by JackBoosY** [comment]
> Right now the easiest way to get vcpkg to work with cmake in VS Code is to add this to `.vscode/settings.json`
> 
> ```json
> {
>     "cmake.configureArgs": [
>         "-DVCPKG_MANIFEST_MODE=ON",
>         "-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake",
>     ],
>     "cmake.generator": "Ninja",
> }
> ```

Please remove thoses settings then press CTRL+SHIFT+P, then click 'vcpkg: Enable vcpkg' and try again.
I may add extra sidebar to provide buttons to control it easily.

**Comment by JackBoosY** [comment]
> I know you're a maintainer of vcpkg 

No longer a maintainer, now is a contributor.

**Comment by JackBoosY** [comment]
Does this problem still occur?

We should add condition to enable manifest mode: was fixed by version 0.2.2.

**Comment by kwsp** [comment]
I reinstalled the extension, and after I click "enable vcpkg", and after selecting the VCPKG root, it now hangs with the message "Enabling vcpkg..."

**Comment by JackBoosY** [comment]
Can you please open `Help` - `Toggle Developer Tools` and provide the output which in `Console`?

**Comment by kwsp** [comment]
I uninstalled the extension and tried again. Didn't reproduce the hang...

**Comment by JackBoosY** [comment]
> I uninstalled the extension and tried again. Didn't reproduce the hang...

Some options are changed in the pre-release version.
Now it's release, I think we shouldn't have this issue for now.

**Comment by kwsp** [comment]
Ok.

I personally only use `vcpkg` in manifest mode, and I found a "happy" `.vscode/settings.json` config that always works for my use case:

```json
{
    "cmake.configureArgs": [
        "-DVCPKG_MANIFEST_MODE=ON",
        "-DCMAKE_TOOLCHAIN_FILE=C:/src/vcpkg/scripts/buildsystems/vcpkg.cmake",
    ],
    "cmake.generator": "Ninja",
    "cmake.buildDirectory": "${workspaceFolder}/build/${buildType}"
}
```
I just need to put this into the source tree, clean up any existing build directories, open VS Code, and everything magically works (aka CMake uses the right toolchain file).
So I think I won't be needing this extension for now. Thanks for your work!

**Comment by JackBoosY** [comment]
I believe 1.0.3 fixed this issue.
