### ISSUE TITLE
How do you set vcpkg.target.defaultTriplet based on Operating System and Platform automatically?

### ISSUE THREAD

**Issue by Pipe-Runner** [JackBoosY/vcpkg-vscode-extension#3]
Is there a way to set `vcpkg.target.defaultTriplet` automatically. I would like to have my setup work seamlessly between linux and macOS and it's a bit of a headache to keep changing `vcpkg.target.defaultTriplet` by myself.

**Comment by JackBoosY** [comment]
Good point!
The default triplet should be automatically changed according to the platform, but there are two problems:
1. The plugin cannot determine x64 / x86 / arm.
2. We also need to handle static triplet manually.

However, I will fix this except the 2 problems by setting it to `<origin_arch>-platform` automatically.

**Comment by JackBoosY** [comment]
After some consideration, if we automatically switch triplet, this may affect the custom triplet.
So we can switch the triplet by adding an option.
Do you agree this?

**Comment by Pipe-Runner** [comment]
> After some consideration, if we automatically switch triplet, this may affect the custom triplet. So we can switch the triplet by adding an option. Do you agree this?

This can be an opt-in feature. The user can choose whether or not they want to use this feature. Keep it disabled by default to avoid unwanted surprises.

**Comment by JackBoosY** [comment]
Okay, please update your plugin then see [document](https://github.com/JackBoosY/vcpkg-vscode-extension/tree/2.0.6#enabledisable-automatically-update-hosttarget-triplet).

**Comment by Pipe-Runner** [comment]
Thanks @JackBoosY. This is a really nice tool.
