### ISSUE TITLE
Extension referring to Window VCPKG path when calling set triplet from linux

### ISSUE THREAD

**Issue by Pipe-Runner** [JackBoosY/vcpkg-vscode-extension#5]
![Screenshot from 2023-11-18 13-11-25](https://github.com/JackBoosY/vcpkg-vscode-extension/assets/19551058/9542143f-651f-4231-b5d1-6cc598f79bc8)

The path shown above is the path on Windows. Also, the path shown is incorrect, even for Windows (my vcpkg is in D:tools/vcpkg. I am getting this error by calling the set host/target triplet on Linux (Ubuntu 22.04).
I am using manifest mode.
Here are the contents of my settings.json

```json
{
  "cmake.configureArgs": [
    "-DVCPKG_APPLOCAL_DEPS=ON",
    "-DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON",
    "-DVCPKG_MANIFEST_MODE=ON",
    "-DVCPKG_TARGET_TRIPLET=x64-linux"
  ],
  "vcpkg.general.enable": true,
  "vcpkg.target.hostTriplet": "-linux",
  // use x64-linx / arm64-osx
  "vcpkg.target.defaultTriplet": "x64-linux",
  "vcpkg.target.useStaticLib": false,
  "cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
  },
  "cmake.debugConfig": {
    "cwd": "${workspaceFolder}"
  },
  "vcpkg.target.installDependencies": true,
  "vcpkg.target.preferSystemLibs": false,
  "vcpkg.target.useManifest": true,
  "vcpkg.target.useDynamicCRT": false,
  "cSpell.words": ["assimp", "glew", "glfw", "imgui", "imguizmo", "opengl"]
}

```

Note: The automatic triplet change is working correctly.

**Comment by JackBoosY** [comment]
Well this caused by `vcpkg.general.vcpkgPath` is not set correctly.

**Comment by Pipe-Runner** [comment]
@JackBoosY Yes, I just checked, you are right about that. But the extension should respect the path I set in settings.json and override the default path while calling this command. What do you think?

**Comment by JackBoosY** [comment]
Extension should set this value (from ENV, etc.) automatically when starting.

**Comment by Pipe-Runner** [comment]
Yes it does, but will that not cause problems when working on different platforms?

**Comment by Pipe-Runner** [comment]
Also, is there possibly a way to use environment variables in the path instead of absolute path?

**Comment by JackBoosY** [comment]
> Also, is there possibly a way to use environment variables in the path instead of absolute path?

Normally it will check `env{VCPKG_ROOT}` first, if it's not set, it will requires you to select vcpkg root path.

**Comment by Pipe-Runner** [comment]
That is odd, because I have `VCPKG_ROOT` root set and as you can see I am also using it in my settings.json, but the extension does not pick up the path for some reason.

**Comment by Pipe-Runner** [comment]
This has some downsides too since it also modifies my CMAKE TOOLCHAIN path from 
```json
"cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
  }
```

to 

```json
"cmake.configureSettings": {
    "CMAKE_TOOLCHAIN_FILE": "/home/myuser/Apps/vcpkg/scripts/buildsystems/vcpkg.cmake"
  }
```

which is an undesirable change.

**Comment by Pipe-Runner** [comment]
> > Also, is there possibly a way to use environment variables in the path instead of absolute path?
> 
> Normally it will check `env{VCPKG_ROOT}` first, if it's not set, it will requires you to select vcpkg root path.

I tried leaving the path field blank in settings and it asks for the path again (asks me to manually set it). What should I put in the path field for it to use the environment variable?

**Comment by JackBoosY** [comment]
Environment variable in `cmake.configureSettings` will not cause this error because it is read by cmake, not the extension.
And all configurations in extensions should not contain environment variables.

**Comment by Pipe-Runner** [comment]
No what I meant was if I choose the path of vcpkg for the extension, it automatically updates the `cmake.configureSettings` path. Which I don't want. The change that I am referring here was done automatically by the extension when I choose the path to my vcpkg.

> This has some downsides too since it also modifies my CMAKE TOOLCHAIN path from
> 
> ```json
> "cmake.configureSettings": {
>     "CMAKE_TOOLCHAIN_FILE": "$env{VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake"
>   }
> ```
> 
> to
> 
> ```json
> "cmake.configureSettings": {
>     "CMAKE_TOOLCHAIN_FILE": "/home/myuser/Apps/vcpkg/scripts/buildsystems/vcpkg.cmake"
>   }
> ```
> 
> which is an undesirable change.

**Comment by JackBoosY** [comment]
I agreed the extension should not change the origin cmake configs.

**Comment by Pipe-Runner** [comment]
If it wants to change it automatically, it is fine, but if the path has been picked up from env variable, then it should use the env variable in the cmake.configureSettings, and if the path was selected by the user, then use the absolute path. Does that make sense? That way you still get to update cmake.configureSettings path automatically and get to use env variable without any problem.

**Comment by Pipe-Runner** [comment]
@JackBoosY Before you make changes, I would suggest this:
- A checkbox which let's you use env variable for vcpkg path resolution. When this checkbox is enabled, the user won't be able to change the path manually. You can give a warning if the variable is not set or not found. When this mode is enabled, the extension can use `$env{VCPKG_ROOT}` anywhere it needs to automatically update `settings.json`
- If the used unchecks the checkbox, then the path field needs to be set by the user. The field cannot be left blank. In this mode, absolute value of the path will be used in `settings.json`. For some edge cases, you can also pre-populate the path field from env variable if available but the user will have full control to change the path and hence the prepopulation of the path will only be used as an initial value in this mode. 

Feel free to brain storm it with me further. This is a great tool and I would like it to be feature complete :)

**Comment by JackBoosY** [comment]
> * A checkbox which let's you use env variable for vcpkg path resolution. When this checkbox is enabled, the user won't be able to change the path manually. You can give a warning if the variable is not set or not found. When this mode is enabled, the extension can use `$env{VCPKG_ROOT}` anywhere it needs to automatically update `settings.json`
> * If the used unchecks the checkbox, then the path field needs to be set by the user. The field cannot be left blank. In this mode, absolute value of the path will be used in `settings.json`. For some edge cases, you can also pre-populate the path field from env variable if available but the user will have full control to change the path and hence the prepopulation of the path will only be used as an initial value in this mode.


This might be a bit complicated, let's keep it simple:
1. If vcpkg toolchain exists in the current cmake configuration and this file exists, this setting is retained.
2. Otherwise, the extension will set the vcpkg toolchain to the cmake configuration according to the set `vcpkg.general.vcpkgPath` (use `env{VCPKG_ROOT}` if present?).

What bothers me is if vcpkg is disabled, should the vcpkg toolchain be deleted?

**Comment by Pipe-Runner** [comment]
> > * A checkbox which let's you use env variable for vcpkg path resolution. When this checkbox is enabled, the user won't be able to change the path manually. You can give a warning if the variable is not set or not found. When this mode is enabled, the extension can use `$env{VCPKG_ROOT}` anywhere it needs to automatically update `settings.json`
> > * If the used unchecks the checkbox, then the path field needs to be set by the user. The field cannot be left blank. In this mode, absolute value of the path will be used in `settings.json`. For some edge cases, you can also pre-populate the path field from env variable if available but the user will have full control to change the path and hence the prepopulation of the path will only be used as an initial value in this mode.
> 
> This might be a bit complicated, let's keep it simple:
> 
> 1. If vcpkg toolchain exists in the current cmake configuration and this file exists, this setting is retained.
> 2. Otherwise, the extension will set the vcpkg toolchain to the cmake configuration according to the set `vcpkg.general.vcpkgPath` (use `env{VCPKG_ROOT}` if present?).
> 
> What bothers me is if vcpkg is disabled, should the vcpkg toolchain be deleted?

I am using this in a project, and I am using Windows, Mac and Linux to build the project from time to time. So give me a few days to get back to you on this. I may be able to help you test out the features correctly, and then you can decide what to add/remove. As of now, things look stable.

**Comment by Pipe-Runner** [comment]
@JackBoosY The first problem I can see is that the path in the user settings is synced across platforms by VS Code. Which leads to the path that is set on Linux showing up on Windows. This is why I suggested the checkbox feature in point 1. I don't know if that is possible, but if it is, then user can know for certain that the path being used is from the env variable. Let's try to solve the cross-platform setup first before we find and solve other issues.

> @JackBoosY Before you make changes, I would suggest this:
> 
> * A checkbox which let's you use env variable for vcpkg path resolution. When this checkbox is enabled, the user won't be able to change the path manually. You can give a warning if the variable is not set or not found. When this mode is enabled, the extension can use `$env{VCPKG_ROOT}` anywhere it needs to automatically update `settings.json`
> * If the used unchecks the checkbox, then the path field needs to be set by the user. The field cannot be left blank. In this mode, absolute value of the path will be used in `settings.json`. For some edge cases, you can also pre-populate the path field from env variable if available but the user will have full control to change the path and hence the prepopulation of the path will only be used as an initial value in this mode.
> 
> Feel free to brain storm it with me further. This is a great tool and I would like it to be feature complete :)
