### ISSUE TITLE
Mac book arm64 is being incorrectly detected as x64-osx

### ISSUE THREAD

**Issue by Pipe-Runner** [JackBoosY/vcpkg-vscode-extension#8]
Using the extension on Macbook with M1 chip leads to incorrect architecture detection. I change the architecture manually and the build works fine.

**Comment by JackBoosY** [comment]
Can you please provide the logs in `DEBUG CONSOLE`?

BTW this issue doesn't happened in my M1 MacBook Pro.

**Comment by Pipe-Runner** [comment]
> Can you please provide the logs in `DEBUG CONSOLE`?
> 
> BTW this issue doesn't happened in my M1 MacBook Pro.

Yes, I'll try it again today and send you the logs.

**Comment by Pipe-Runner** [comment]
@JackBoosY It seems there was some bug; sometimes the extension automatically changes when I do a git pull, and sometimes it doesn't, so I disabled and re-enabled vcpkg for the extension to set the host triplet correctly. 
Also, the architecture it is setting is correct.
Using `set target triplet` command throws the following error btw:

<img width="395" alt="image" src="https://github.com/JackBoosY/vcpkg-vscode-extension/assets/19551058/e0f740db-3275-4d34-8b7c-a86067dfa984">

**Comment by JackBoosY** [comment]
> @JackBoosY It seems there was some bug; sometimes the extension automatically changes when I do a git pull, and sometimes it doesn't, so I disabled and re-enabled vcpkg for the extension to set the host triplet correctly. Also, the architecture it is setting is correct. Using `set target triplet` command throws the following error btw:
> 
> <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/19551058/293441735-e0f740db-3275-4d34-8b7c-a86067dfa984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzcwOTEsIm5iZiI6MTcwNDQzNjc5MSwicGF0aCI6Ii8xOTU1MTA1OC8yOTM0NDE3MzUtZTBmNzQwZGItMzI3NS00ZDM0LThiN2MtYTg2MDY3ZGZhOTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2Mzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYmM0NTViMjNkOWI5N2JlNGRjMTFiMmYzOTY3M2NiZWI1YTUzZGRmZDI2YWE3ZGZiNGI4YzFjNmZhMzkxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5hNh9B0aIdzeMjuR3IdiOc8zGb-Ac8RmXOD_2gLsCY8">

It seems that the vcpkg root is incorrect, can you please provide the debug logs?

**Comment by Pipe-Runner** [comment]
> > @JackBoosY It seems there was some bug; sometimes the extension automatically changes when I do a git pull, and sometimes it doesn't, so I disabled and re-enabled vcpkg for the extension to set the host triplet correctly. Also, the architecture it is setting is correct. Using `set target triplet` command throws the following error btw:
> > <img alt="image" width="395" src="https://private-user-images.githubusercontent.com/19551058/293441735-e0f740db-3275-4d34-8b7c-a86067dfa984.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzcwOTEsIm5iZiI6MTcwNDQzNjc5MSwicGF0aCI6Ii8xOTU1MTA1OC8yOTM0NDE3MzUtZTBmNzQwZGItMzI3NS00ZDM0LThiN2MtYTg2MDY3ZGZhOTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA2Mzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlYmM0NTViMjNkOWI5N2JlNGRjMTFiMmYzOTY3M2NiZWI1YTUzZGRmZDI2YWE3ZGZiNGI4YzFjNmZhMzkxMjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5hNh9B0aIdzeMjuR3IdiOc8zGb-Ac8RmXOD_2gLsCY8">
> 
> It seems that the vcpkg root is incorrect, can you please provide the debug logs?

Does that appear in the output window? I am not sure how to get debug logs for an extension.

**Comment by JackBoosY** [comment]
Use [this package](https://github.com/JackBoosY/vcpkg-vscode-extension/files/14061140/vcpkg-cmake-tools-2.0.9.vsix.zip) instead, then find the logs in `OUTPUT` - `vcpkg` channel.

**Comment by JackBoosY** [comment]
Ping @Pipe-Runner

**Comment by Pipe-Runner** [comment]
Currently a bit occupied. I will try to collect the logs soon.
@JackBoosY

**Comment by JackBoosY** [comment]
@Pipe-Runner Any result after our Chinese new year?

**Comment by Pipe-Runner** [comment]
Unfortunately I have been occupied with part time work and thesis. Can we temporarily close this issue until it gets reported again?

**Comment by JackBoosY** [comment]
ok
